---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: causalrca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: causalrca
  template:
    metadata:
      labels:
        app: causalrca
    spec:
      containers:
      - name: causalrca
        image: hyluvavu/adapted_causalrca
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: causalrca-service
spec:
  selector:
    app: causalrca
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
