{
 "title": "AD & RCA",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "anomaly_time_variable",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(bucket: \"CausalRCA\", tag: \"anomaly_time\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Detected Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ELBD\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"elbd_results\")\r\n    |> filter(fn: (r) => r._field == \"anomaly\")\r\n"
    }
   ]
  },
  {
   "title": "Most Possible Faulty Microservices",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"CausalRCA\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"causalrca_results\")\r\n    |> filter(fn: (r) => r._field == \"metric\" or r._field == \"score\")\r\n    |> filter(fn: (r) => r[\"anomaly_time\"] == \"${anomaly_time_variable}\")\r\n    |> filter(fn: (r) => r[\"granularity\"] == \"coarse\")\r\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Most Possible Root Cause Metrics of the Most Possible Faulty Microservice",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"CausalRCA\")\r\n    |> range(start: -1h)\r\n    |> filter(fn: (r) => r._measurement == \"causalrca_results\")\r\n    |> filter(fn: (r) => r._field == \"metric\" or r._field == \"score\")\r\n    |> filter(fn: (r) => r[\"anomaly_time\"] == \"${anomaly_time_variable}\")\r\n    |> filter(fn: (r) => r[\"granularity\"] == \"fine\")\r\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  }
 ]
}